#import "@preview/touying:0.6.1": speaker-note

== Introduction to Control Units

- The control unit directs CPU operations and generates control signals.
- Control-unit types:
  - *Unpipelined hardwired (Von Neumann style):* Hardware generates control signals directly.
  - *Microprogrammed (Wilkes style):* Stored microinstructions generate control signals.
  - *Pipelined hardwired:* Pipeline stages improve performance.
- All generate control signals, but differ in implementation and use.

#speaker-note[
  Control units generate the signals required to execute instructions. This lecture compares hardwired and microprogrammed designs.
]

== Unpipelined Hardwired Control Unit

- Control signals are generated by combinational logic from instruction and status bits.
- An FSM maps control signals to states.
- Instructions directly trigger hardware control signals.

#speaker-note[
  Hardwired control is fast because it uses combinational circuits, but it is less adaptable. FSM states correspond to control signals.
]

== Advantages of Hardwired Control Units

- Fast execution through direct signal generation
- Well suited to simple instruction sets such as RISC
- Low latency because control signals do not need to be fetched from memory

== Disadvantages of Hardwired Control Units

- Inflexible: modifications require hardware changes.
- Complex to design for extensive instruction sets such as CISC.

== Microprogrammed Control Unit

- A stored microprogram generates control signals.
- Each machine instruction is divided into smaller microinstructions.
- A microinstruction ($"μI"$) is a set of data- and resource-independent micro-operations that execute in one cycle.
- Micro-operations ($"μO"$) are control signals for processor data flow.

== Microprogrammed Control Unit Components

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  [#image("media/mpcuarchitecture.png", width: 100%)],
  [
    - *Control memory (CM):* Stores microinstructions.
    - *Micro-sequencer (μS):* Fetches microinstructions.
    - *Microinstruction register (μIR):* Stores the current microinstruction.
    - *Microinstruction program counter (μPC):* Tracks the current microinstruction.
  ],
)

== Advantages of Microprogrammed Control Units

- Flexible: Update the microprogram instead of changing hardware.
- Simplifies implementation of complex instruction sets.
- Easier to debug because control logic is in microcode.
- Makes instruction-set expansion easier.
- Requires less control-specific hardware.
- Can emulate different instruction sets.

== Advantages of Microprogrammed Control Units

- Flexible: Change the microprogram to update control behavior.
- Simplifies complex instruction-set implementations.
- Centralized logic makes errors easier to find.
- Supports new instructions and instruction-set emulation.
- Requires less control-specific hardware.

== Disadvantages of Microprogrammed Control Units

- Slower than hardwired units because microinstructions must be fetched.
- Requires additional memory for the microprogram.

== Key Differences Between Control Units

#figure(
  table(
    columns: 4,
    align: left,
    table.header([*Feature*], [*Unpipelined hardwired*], [*Microprogrammed*], [*Pipelined hardwired*]),
    [Control signal generation], [Combinational logic], [Microinstructions], [Combinational logic],
    [Flexibility], [Low], [High], [Low],
    [Best suited for], [RISC], [CISC], [RISC/CISC],
    [Memory usage], [No extra memory], [Microprogram memory], [Intermediate storage],
    [CPI], [1], [>1], [1],
    [Cycle time], [Longer], [Shorter (sequential)], [Short (parallel)],
  ),
)