module top;
    reg clk;
    reg  [0:0] x;
    reg  [0:0] rst_n;
    wire [0:0] y;
    moore_fsm dut(.clk(clk), .x(x), .rst_n(rst_n), .y(y));
    initial begin
        clk = 0; #1;
        x = 1'b1; rst_n = 1'b0; #2;
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=0 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b0; #2;
        $display("\n[CHECKER]moore_fsm|cycle=1 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=1 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b0; #2;
        $display("\n[CHECKER]moore_fsm|cycle=2 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=2 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=3 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=3 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=4 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=4 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=5 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=5 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=6 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=6 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=7 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=7 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=8 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=8 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=9 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=9 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=10 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=10 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=11 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=11 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=12 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=12 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=13 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=13 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=14 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=14 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=15 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=15 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=16 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=16 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=17 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=17 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=18 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=18 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=19 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=19 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=20 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=20 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=21 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=21 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=22 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=22 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=23 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=23 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=24 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=24 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=25 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=25 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=26 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=26 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=27 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=27 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=28 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=28 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=29 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=29 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=30 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=30 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=31 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=31 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=32 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=32 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=33 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=33 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=34 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=34 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=35 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=35 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=36 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=36 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=37 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=37 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=38 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=38 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=39 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=39 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=40 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=40 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=41 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=41 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=42 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=42 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=43 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=43 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=44 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=44 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=45 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=45 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=46 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=46 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=47 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=47 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=48 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=48 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=49 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=49 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=50 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=50 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=51 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=51 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=52 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=52 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=53 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=53 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=54 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=54 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=55 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=55 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=56 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=56 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=57 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=57 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=58 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=58 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=59 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=59 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=60 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=60 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=61 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=61 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=62 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=62 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=63 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=63 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=64 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=64 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=65 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=65 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=66 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=66 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=67 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=67 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=68 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=68 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=69 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=69 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b0; #2;
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=70 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b0; #2;
        $display("\n[CHECKER]moore_fsm|cycle=71 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=71 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=72 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=72 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=73 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=73 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=74 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=74 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=75 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=75 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=76 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=76 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=77 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=77 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=78 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=78 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=79 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=79 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=80 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=80 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=81 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=81 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=82 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=82 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=83 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=83 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=84 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=84 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=85 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=85 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=86 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=86 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=87 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=87 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=88 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=88 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=89 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=89 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=90 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=90 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=91 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=91 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=92 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=92 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=93 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=93 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=94 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=94 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=95 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=95 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=96 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=96 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=97 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=97 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=98 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=98 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=99 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=99 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=100 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=100 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=101 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=101 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=102 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=102 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=103 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=103 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=104 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=104 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=105 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=105 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=106 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=106 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=107 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=107 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=108 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=108 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=109 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=109 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=110 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=110 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=111 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=111 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=112 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=112 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=113 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=113 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=114 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=114 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=115 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=115 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=116 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=116 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=117 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=117 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=118 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=118 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=119 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=119 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=120 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=120 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=121 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=121 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=122 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=122 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=123 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=123 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=124 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=124 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=125 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=125 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=126 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=126 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=127 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=127 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=128 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=128 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=129 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=129 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=130 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=130 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=131 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=131 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=132 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=132 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=133 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=133 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=134 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=134 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=135 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=135 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=136 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=136 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=137 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=137 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=138 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=138 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=139 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=139 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=140 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=140 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=141 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=141 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=142 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=142 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=143 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=143 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=144 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=144 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=145 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=145 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=146 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=146 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=147 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=147 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=148 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=148 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=149 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=149 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b0; #2;
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=150 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=151 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=151 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=152 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=152 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=153 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=153 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=154 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=154 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=155 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=155 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=156 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=156 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=157 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=157 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=158 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=158 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=159 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=159 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=160 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=160 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=161 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=161 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=162 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=162 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=163 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=163 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=164 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=164 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=165 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=165 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=166 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=166 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=167 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=167 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=168 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=168 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=169 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=169 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=170 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=170 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=171 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=171 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=172 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=172 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=173 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=173 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=174 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=174 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=175 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=175 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=176 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=176 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=177 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=177 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=178 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=178 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=179 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=179 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=180 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=180 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=181 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=181 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=182 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=182 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=183 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=183 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=184 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=184 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=185 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=185 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=186 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=186 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=187 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=187 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=188 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=188 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=189 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=189 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=190 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=190 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=191 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=191 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=192 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=192 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=193 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=193 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=194 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=194 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=195 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=195 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=196 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=196 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=197 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=197 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=198 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=198 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=199 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=199 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=200 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=200 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=201 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=201 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=202 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=202 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=203 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=203 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=204 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=204 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=205 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=205 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=206 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=206 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=207 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=207 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=208 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=208 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=209 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=209 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=210 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=210 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=211 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=211 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=212 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=212 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=213 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=213 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=214 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=214 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=215 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=215 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=216 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=216 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=217 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=217 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=218 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=218 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=219 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=219 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=220 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=220 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=221 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=221 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=222 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=222 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=223 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=223 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=224 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=224 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=225 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=225 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=226 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=226 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=227 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=227 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=228 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=228 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=229 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=229 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=230 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=230 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=231 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=231 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=232 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=232 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=233 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=233 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=234 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=234 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=235 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=235 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=236 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=236 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=237 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=237 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b0; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=238 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=238 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        x = 1'b1; rst_n = 1'b1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=239 pre x=%b rst_n=%b|y=%b", x, rst_n, y);
        clk = 1; #2;
        $display("\n[CHECKER]moore_fsm|cycle=239 post x=%b rst_n=%b|y=%b", x, rst_n, y);
        #2; clk = 0; #2;
        $finish;
    end
endmodule
