module top;
    reg clk;
    reg  [0:0] i;
    wire [0:0] o;
    ba dut(.clk(clk), .i(i), .o(o));
    initial begin
        clk = 0; #1;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=0 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=0 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=1 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=1 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=2 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=2 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=3 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=3 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=4 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=4 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=5 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=5 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=6 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=6 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=7 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=7 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=8 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=8 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=9 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=9 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=10 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=10 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=11 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=11 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=12 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=12 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=13 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=13 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=14 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=14 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=15 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=15 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=16 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=16 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=17 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=17 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=18 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=18 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=19 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=19 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=20 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=20 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=21 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=21 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=22 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=22 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=23 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=23 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=24 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=24 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=25 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=25 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=26 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=26 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=27 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=27 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=28 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=28 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=29 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=29 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=30 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=30 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=31 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=31 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=32 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=32 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=33 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=33 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=34 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=34 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=35 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=35 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=36 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=36 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=37 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=37 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=38 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=38 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=39 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=39 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=40 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=40 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=41 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=41 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=42 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=42 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=43 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=43 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=44 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=44 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=45 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=45 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=46 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=46 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=47 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=47 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=48 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=48 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=49 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=49 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=50 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=50 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=51 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=51 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=52 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=52 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=53 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=53 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=54 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=54 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=55 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=55 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=56 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=56 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=57 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=57 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=58 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=58 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=59 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=59 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=60 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=60 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=61 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=61 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=62 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=62 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=63 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=63 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=64 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=64 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=65 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=65 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=66 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=66 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=67 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=67 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=68 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=68 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=69 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=69 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=70 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=70 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=71 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=71 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=72 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=72 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=73 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=73 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=74 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=74 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=75 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=75 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=76 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=76 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=77 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=77 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=78 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=78 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=79 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=79 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=80 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=80 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=81 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=81 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=82 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=82 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=83 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=83 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=84 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=84 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=85 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=85 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=86 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=86 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=87 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=87 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=88 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=88 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=89 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=89 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=90 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=90 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=91 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=91 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=92 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=92 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=93 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=93 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=94 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=94 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=95 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=95 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=96 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=96 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=97 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=97 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=98 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=98 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=99 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=99 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=100 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=100 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=101 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=101 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=102 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=102 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=103 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=103 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=104 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=104 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=105 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=105 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=106 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=106 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=107 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=107 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=108 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=108 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=109 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=109 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=110 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=110 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=111 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=111 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=112 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=112 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=113 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=113 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=114 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=114 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=115 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=115 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=116 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=116 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=117 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=117 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=118 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=118 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=119 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=119 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=120 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=120 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=121 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=121 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=122 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=122 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=123 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=123 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=124 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=124 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=125 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=125 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=126 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=126 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=127 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=127 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=128 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=128 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=129 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=129 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=130 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=130 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=131 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=131 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=132 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=132 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=133 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=133 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=134 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=134 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=135 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=135 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=136 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=136 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=137 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=137 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=138 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=138 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=139 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=139 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=140 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=140 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=141 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=141 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=142 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=142 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=143 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=143 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=144 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=144 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=145 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=145 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=146 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=146 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=147 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=147 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=148 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=148 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=149 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=149 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=150 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=150 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=151 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=151 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=152 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=152 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=153 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=153 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=154 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=154 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=155 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=155 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=156 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=156 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=157 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=157 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=158 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=158 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=159 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=159 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=160 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=160 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=161 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=161 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=162 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=162 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=163 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=163 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=164 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=164 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=165 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=165 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=166 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=166 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=167 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=167 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=168 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=168 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=169 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=169 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=170 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=170 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=171 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=171 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=172 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=172 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=173 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=173 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=174 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=174 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=175 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=175 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=176 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=176 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=177 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=177 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=178 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=178 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=179 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=179 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=180 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=180 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=181 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=181 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=182 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=182 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=183 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=183 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=184 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=184 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=185 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=185 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=186 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=186 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=187 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=187 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=188 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=188 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=189 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=189 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=190 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=190 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=191 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=191 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=192 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=192 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=193 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=193 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=194 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=194 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=195 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=195 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b0; #2;
        $display("\n[CHECKER]ba|cycle=196 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=196 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=197 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=197 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=198 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=198 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        i = 1'b1; #2;
        $display("\n[CHECKER]ba|cycle=199 pre i=%b|o=%b", i, o);
        clk = 1; #2;
        $display("\n[CHECKER]ba|cycle=199 post i=%b|o=%b", i, o);
        #2; clk = 0; #2;
        $finish;
    end
endmodule
