module top;
    reg clk = 0, rst_n = 0, write = 0, multiply = 0, display = 0;
    reg [7:0] a = 0;
    reg [3:0] b = 0;
    wire [11:0] out;
    sequential_multiplier dut(.clk(clk), .rst_n(rst_n), .a(a), .b(b), .write(write), .multiply(multiply), .display(display), .out(out));
    always #10 clk = ~clk;
    initial begin
        #100; rst_n = 1;
        a = 0; b = 0; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 255; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 1; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 255; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 1; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 128; b = 8; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 170; b = 5; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 85; b = 10; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 165; b = 4; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 202; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 37; b = 3; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 187; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 109; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 44; b = 13; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 214; b = 2; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 123; b = 2; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 217; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 63; b = 7; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 31; b = 12; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 25; b = 7; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 23; b = 4; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 148; b = 13; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 73; b = 3; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 157; b = 5; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 52; b = 6; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 190; b = 3; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 32; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 105; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 218; b = 10; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 238; b = 14; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 185; b = 9; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 127; b = 5; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 124; b = 2; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 153; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 175; b = 14; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 147; b = 2; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 60; b = 13; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 84; b = 10; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 77; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 215; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 39; b = 10; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 174; b = 11; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 254; b = 14; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 35; b = 2; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 138; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 33; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 158; b = 14; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 145; b = 12; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 177; b = 0; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 236; b = 11; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 86; b = 3; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 252; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 111; b = 9; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 66; b = 7; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 203; b = 12; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 254; b = 2; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 85; b = 14; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 205; b = 8; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 70; b = 13; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 142; b = 13; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 183; b = 12; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 118; b = 4; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 42; b = 5; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 77; b = 7; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 119; b = 0; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 248; b = 5; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 134; b = 9; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 2; b = 4; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 214; b = 11; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 163; b = 4; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 27; b = 14; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 200; b = 12; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 204; b = 12; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 53; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 205; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 97; b = 2; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 106; b = 14; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 83; b = 3; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 174; b = 1; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 52; b = 0; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 77; b = 3; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 186; b = 0; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 36; b = 6; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 192; b = 4; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 129; b = 11; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 186; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 62; b = 3; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 249; b = 14; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 245; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 159; b = 2; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 73; b = 3; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 175; b = 8; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 245; b = 5; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 11; b = 6; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 185; b = 4; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 13; b = 9; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 46; b = 8; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 187; b = 5; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 182; b = 7; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 168; b = 7; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 99; b = 7; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 205; b = 7; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 102; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 182; b = 0; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 14; b = 8; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 241; b = 8; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 99; b = 11; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 228; b = 11; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 186; b = 2; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 112; b = 3; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 116; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 100; b = 10; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 104; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 0; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 176; b = 2; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 61; b = 12; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 102; b = 15; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 91; b = 13; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 170; b = 2; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        a = 202; b = 14; #20; write = 1; #25; write = 0; multiply = 1; #20; multiply = 0; display = 1; #30;
        $display("\n[CHECKER]sequential_multiplier|a=%b b=%b|out=%b", a, b, out); display = 0;
        $finish;
    end
endmodule
