== Problems with Polling

- Consumes CPU time.
- Efficiency depends on the polling interval:
  - Polling too often consumes CPU time.
  - Polling too slowly delays device responses.
- Polling is synchronous and unsuitable for many real-time systems.

== Interrupt Systems

- Interrupts let an asynchronous system handle asynchronous events.
- An interrupt is a hardware or software signal indicating an event that needs immediate attention.
- When a device requests service, the CPU suspends its current task, runs an interrupt service routine (ISR), then resumes the task.
- *Advantages:*
  - The CPU handles devices only when needed.
  - Time-sensitive events receive prompt attention.
  - Multiple tasks can be handled without wasting cycles on polling.

== Types of Interrupts

- Hardware interrupts: generated by devices or the CPU.
- Software interrupts: generated by a program.
- Maskable interrupts: can be enabled or disabled.
- Non-maskable interrupts: cannot be disabled.
- Internal interrupts: generated by the CPU.
- External interrupts: generated by external devices.

== Interrupt-System Concepts

- Interrupt classes and levels depend on the interrupt source.
- Priority determines which interrupt the CPU handles first.
- Identification determines an interrupt's level and priority.
- Interrupts may be disabled globally or selectively in critical sections.
- The CPU saves its current context and restores it after handling the interrupt.
- The CPU communicates with the I/O device.
- Interrupt handlers should execute as briefly as possible.

== Interrupt-Handling Mechanism

- Interrupt request (IRQ) lines
- Interrupt vector table (IVT)
- Interrupt service routines (ISRs)
- Prioritization and nesting
- Context switching

== Interrupt Request (IRQ) Lines

- IRQ lines are hardware connections through which I/O devices signal the CPU.
- When a device needs attention, it asserts its IRQ signal.
- The CPU identifies the source and starts the associated ISR.

== Interrupt Vector Table (IVT)

- The IVT is a memory table containing jump instructions or addresses for ISRs.
- It provides a fast lookup from an interrupt to its handler.
- When an interrupt occurs, the CPU reads the appropriate entry and transfers control to the ISR.

== Interrupt Service Routine (ISR)

- An ISR is a special function executed in response to an interrupt.
- It handles the associated task, such as data transfer or a status update.
- An ISR commonly disables interrupts at entry (`cli`), runs its handler, and ends with a return-from-interrupt instruction (`reti`).

== Prioritization and Nesting

- High-priority interrupts can preempt lower-priority handlers.
- Nesting allows one interrupt to trigger while another handler is running.
- This improves responsiveness and lets critical events take priority.

== Context Switching in Interrupt Handling

- The CPU saves its current state, including registers and program counter, before handling an interrupt.
- Process:
  + Save the interrupted task's context.
  + Execute the ISR.
  + Restore the context after the ISR completes.
- The CPU then resumes exactly where it was interrupted.